# Site settings
collections:
  kb:
    output: true
    permalink: /:path/:title/

# Build settings & gem packages
markdown: kramdown
highlighter: rouge
gems: 
  - jekyll-sitemap
  - jekyll-seo-tag

# KB Page Categorization
top-categories: [Analog, Digital]
sub-categories: [Fundamentals, SDLC, tools]

# SEO: from github.com/jekyll/jekyll-seo-tag
title: Gent-Systems
description: Engineering creatively. Learning and development through open-source.
url: http://gent-systems.com
author: John Gentile
logo: /assets/images/Gent-systems_icon_black.png